"""Plugin specifications and data"""

import os
import random

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
PLUGINS_ITEMS_DIR = os.path.normpath(os.path.join(PROJECT_ROOT, "assets", "plugins", "plugins-items"))


def get_plugins_data():
    """Return initial plugin specifications (fast loading)"""
    return [
        {
            'id': 'bleachbit',
            'name': 'BleachBit',
            'desc': 'System cleaner to free disk space and guard your privacy.',
            'pkg': 'bleachbit',
            'cmd': 'bleachbit',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'BleachBit.png'),
            'category': 'System',
        },
        {
            'id': 'gparted',
            'name': 'GParted',
            'desc': 'Partition editor for graphically managing disk partitions.',
            'pkg': 'gparted',
            'cmd': 'gparted',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gparted.jpeg'),
            'category': 'System',
        },
        {
            'id': 'btop',
            'name': 'btop',
            'desc': 'Modern resource monitor for CPU, memory, disks, network.',
            'pkg': 'btop',
            'cmd': 'btop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'btop.png'),
            'category': 'Monitor',
        },
        {
            'id': 'code',
            'name': 'Visual Studio Code',
            'desc': 'Powerful source code editor with IntelliSense and debugging.',
            'pkg': 'code',
            'cmd': 'code',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vscode.png'),
            'category': 'Development',
        },
        {
            'id': 'firefox',
            'name': 'Firefox',
            'desc': 'Fast, private & safe web browser from Mozilla.',
            'pkg': 'firefox',
            'cmd': 'firefox',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'firefox.png'),
            'category': 'Internet',
        },
        {
            'id': 'vlc',
            'name': 'VLC Media Player',
            'desc': 'Universal multimedia player for all formats.',
            'pkg': 'vlc',
            'cmd': 'vlc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vlc.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'steam',
            'name': 'Steam',
            'desc': 'Digital distribution platform for PC gaming.',
            'pkg': 'steam',
            'cmd': 'steam',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'steam.png'),
            'category': 'Games',
        },
        {
            'id': 'libreoffice',
            'name': 'LibreOffice',
            'desc': 'Free and open-source office productivity software suite.',
            'pkg': 'libreoffice-fresh',
            'cmd': 'libreoffice',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'libreoffice.png'),
            'category': 'Office',
        },
    ]


def get_all_plugins_data():
    """Return all plugin specifications (lazy loading)"""
    plugins = [
        # System Tools
        {
            'id': 'bleachbit',
            'name': 'BleachBit',
            'desc': 'System cleaner to free disk space and guard your privacy.',
            'pkg': 'bleachbit',
            'cmd': 'bleachbit',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'BleachBit.png'),
            'category': 'System',
        },
        {
            'id': 'timeshift',
            'name': 'Timeshift',
            'desc': 'System restore utility for Linux.',
            'pkg': 'timeshift',
            'cmd': 'timeshift-gtk',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'timeshift.png'),
            'category': 'Backup',
        },
        {
            'id': 'baobab',
            'name': 'Disk Usage Analyzer',
            'desc': 'Visualize disk usage and identify large folders/files.',
            'pkg': 'baobab',
            'cmd': 'baobab',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'diskusageanalyzer.png'),
            'category': 'System',
        },
        {
            'id': 'deja-dup',
            'name': 'Déjà Dup (Backups)',
            'desc': 'Simple backups for GNOME with cloud support.',
            'pkg': 'deja-dup',
            'cmd': 'deja-dup',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'DejaDup.png'),
            'category': 'Backup',
        },
        {
            'id': 'gparted',
            'name': 'GParted',
            'desc': 'Partition editor for graphically managing disk partitions.',
            'pkg': 'gparted',
            'cmd': 'gparted',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gparted.jpeg'),
            'category': 'System',
        },
        {
            'id': 'gnome-disk-utility',
            'name': 'GNOME Disks',
            'desc': 'Manage disks and media — partition, format and benchmark.',
            'pkg': 'gnome-disk-utility',
            'cmd': 'gnome-disks',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gnomedisk.jpeg'),
            'category': 'System',
        },
        {
            'id': 'pavucontrol',
            'name': 'PulseAudio Volume Control',
            'desc': 'Advanced audio mixer for PulseAudio.',
            'pkg': 'pavucontrol',
            'cmd': 'pavucontrol',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'pulseaudio.png'),
            'category': 'System',
        },
        {
            'id': 'system-config-printer',
            'name': 'Printers',
            'desc': 'Configure printers and manage print jobs.',
            'pkg': 'system-config-printer',
            'cmd': 'system-config-printer',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'printers.png'),
            'category': 'System',
        },

        # System Monitoring
        {
            'id': 'btop',
            'name': 'btop',
            'desc': 'Modern resource monitor for CPU, memory, disks, network.',
            'pkg': 'btop',
            'cmd': 'btop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'btop.png'),
            'category': 'Monitor',
        },
        {
            'id': 'htop',
            'name': 'htop',
            'desc': 'Interactive process viewer and system monitor.',
            'pkg': 'htop',
            'cmd': 'htop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'htop.png'),
            'category': 'Monitor',
        },
        {
            'id': 'gnome-system-monitor',
            'name': 'GNOME System Monitor',
            'desc': 'Graphical system monitor for processes and resources.',
            'pkg': 'gnome-system-monitor',
            'cmd': 'gnome-system-monitor',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gnomesystem.jpeg'),
            'category': 'Monitor',
        },

        # GPU Tools
        {
            'id': 'nvidia-settings',
            'name': 'NVIDIA Settings',
            'desc': 'Configure NVIDIA drivers and GPU options.',
            'pkg': 'nvidia-settings',
            'cmd': 'nvidia-settings',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nvideasettings.jpeg'),
            'category': 'GPU',
        },
        {
            'id': 'nvtop',
            'name': 'nvtop',
            'desc': 'NVIDIA/AMD Intel GPU process monitor (requires supported GPU).',
            'pkg': 'nvtop',
            'cmd': 'nvtop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nvtop.png'),
            'category': 'GPU',
        },

        # Utilities
        {
            'id': 'simple-scan',
            'name': 'Document Scanner',
            'desc': 'Scan documents and photos with a simple interface.',
            'pkg': 'simple-scan',
            'cmd': 'simple-scan',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'documentscanner.png'),
            'category': 'Utility',
        },
        {
            'id': 'file-roller',
            'name': 'Archive Manager',
            'desc': 'Create and extract archives (zip, tar, etc.).',
            'pkg': 'file-roller',
            'cmd': 'file-roller',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'achive.png'),
            'category': 'Utility',
        },
        {
            'id': 'calibre',
            'name': 'Calibre',
            'desc': 'Powerful and easy to use e-book manager.',
            'pkg': 'calibre',
            'cmd': 'calibre',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'calibre.png'),
            'category': 'Utility',
        },

        # Multimedia
        {
            'id': 'vlc',
            'name': 'VLC Media Player',
            'desc': 'Universal multimedia player for all formats.',
            'pkg': 'vlc',
            'cmd': 'vlc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vlc.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'audacity',
            'name': 'Audacity',
            'desc': 'Free audio editor and recorder for all platforms.',
            'pkg': 'audacity',
            'cmd': 'audacity',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'audacity.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'obs-studio',
            'name': 'OBS Studio',
            'desc': 'Free and open source software for video recording.',
            'pkg': 'obs-studio',
            'cmd': 'obs',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'obs.png'),
            'category': 'Multimedia',
        },

        # Graphics
        {
            'id': 'gimp',
            'name': 'GIMP',
            'desc': 'GNU Image Manipulation Program for photo editing.',
            'pkg': 'gimp',
            'cmd': 'gimp',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gimp.png'),
            'category': 'Graphics',
        },
        {
            'id': 'blender',
            'name': 'Blender',
            'desc': '3D modeling, animation, and rendering software.',
            'pkg': 'blender',
            'cmd': 'blender',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'blender.png'),
            'category': 'Graphics',
        },

        # Internet & Communication
        {
            'id': 'thunderbird',
            'name': 'Thunderbird',
            'desc': 'Free email client and news reader.',
            'pkg': 'thunderbird',
            'cmd': 'thunderbird',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'thunderbird.png'),
            'category': 'Internet',
        },
        {
            'id': 'transmission',
            'name': 'Transmission',
            'desc': 'Fast, easy, and free BitTorrent client.',
            'pkg': 'transmission-gtk',
            'cmd': 'transmission-gtk',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'transmission.png'),
            'category': 'Internet',
        },
        {
            'id': 'qbittorrent',
            'name': 'qBittorrent',
            'desc': 'Open source BitTorrent client written in C++.',
            'pkg': 'qbittorrent',
            'cmd': 'qbittorrent',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'qbittorrent.png'),
            'category': 'Internet',
        },

        # Development Tools
        {
            'id': 'code',
            'name': 'Visual Studio Code',
            'desc': 'Powerful source code editor with IntelliSense and debugging.',
            'pkg': 'code',
            'cmd': 'code',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vscode.png'),
            'category': 'Development',
        },
        {
            'id': 'git',
            'name': 'Git',
            'desc': 'Distributed version control system for tracking changes.',
            'pkg': 'git',
            'cmd': 'git',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'git.png'),
            'category': 'Development',
        },
        {
            'id': 'nodejs',
            'name': 'Node.js',
            'desc': 'JavaScript runtime built on Chrome\'s V8 JavaScript engine.',
            'pkg': 'nodejs',
            'cmd': 'node',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nodejs.png'),
            'category': 'Development',
        },
        {
            'id': 'python',
            'name': 'Python',
            'desc': 'High-level programming language for general-purpose programming.',
            'pkg': 'python',
            'cmd': 'python',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'python.png'),
            'category': 'Development',
        },

        # Office & Productivity
        {
            'id': 'libreoffice',
            'name': 'LibreOffice',
            'desc': 'Free and open-source office productivity software suite.',
            'pkg': 'libreoffice-fresh',
            'cmd': 'libreoffice',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'libreoffice.png'),
            'category': 'Office',
        },
        {
            'id': 'onlyoffice',
            'name': 'OnlyOffice',
            'desc': 'Complete office suite with document, spreadsheet and presentation editors.',
            'pkg': 'onlyoffice-bin',
            'cmd': 'onlyoffice-desktopeditors',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'onlyoffice.png'),
            'category': 'Office',
        },
        {
            'id': 'notion',
            'name': 'Notion',
            'desc': 'All-in-one workspace for notes, tasks, wikis, and databases.',
            'pkg': 'notion-app',
            'cmd': 'notion-app',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'notion.png'),
            'category': 'Office',
        },

        # Games
        {
            'id': 'steam',
            'name': 'Steam',
            'desc': 'Digital distribution platform for PC gaming.',
            'pkg': 'steam',
            'cmd': 'steam',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'steam.png'),
            'category': 'Games',
        },
        {
            'id': 'lutris',
            'name': 'Lutris',
            'desc': 'Gaming platform for Linux with Wine and Proton support.',
            'pkg': 'lutris',
            'cmd': 'lutris',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'lutris.png'),
            'category': 'Games',
        },
        {
            'id': 'heroic',
            'name': 'Heroic Games Launcher',
            'desc': 'Native GOG, Epic Games and Amazon Prime Games launcher.',
            'pkg': 'heroic-games-launcher-bin',
            'cmd': 'heroic',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'heroic.png'),
            'category': 'Games',
        },

        # Security & Privacy
        {
            'id': 'keepassxc',
            'name': 'KeePassXC',
            'desc': 'Cross-platform community-driven port of KeePass password manager.',
            'pkg': 'keepassxc',
            'cmd': 'keepassxc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'keepassxc.png'),
            'category': 'Security',
        },
        {
            'id': 'bitwarden',
            'name': 'Bitwarden',
            'desc': 'Secure and free password manager for all of your devices.',
            'pkg': 'bitwarden',
            'cmd': 'bitwarden',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'bitwarden.png'),
            'category': 'Security',
        },
        {
            'id': 'tor-browser',
            'name': 'Tor Browser',
            'desc': 'Private web browser that protects your anonymity.',
            'pkg': 'tor-browser',
            'cmd': 'tor-browser',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'tor.png'),
            'category': 'Security',
        },

        # Communication
        {
            'id': 'discord',
            'name': 'Discord',
            'desc': 'Voice, video and text chat app for communities and friends.',
            'pkg': 'discord',
            'cmd': 'discord',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'discord.png'),
            'category': 'Communication',
        },
        {
            'id': 'telegram',
            'name': 'Telegram Desktop',
            'desc': 'Fast and secure desktop messaging app.',
            'pkg': 'telegram-desktop',
            'cmd': 'telegram-desktop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'telegram.png'),
            'category': 'Communication',
        },
        {
            'id': 'signal',
            'name': 'Signal',
            'desc': 'Private messenger with end-to-end encryption.',
            'pkg': 'signal-desktop',
            'cmd': 'signal-desktop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'signal.png'),
            'category': 'Communication',
        },
        {
            'id': 'zoom',
            'name': 'Zoom',
            'desc': 'Video conferencing and web conferencing service.',
            'pkg': 'zoom',
            'cmd': 'zoom',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'zoom.png'),
            'category': 'Communication',
        },

        # Education & Learning
        {
            'id': 'anki',
            'name': 'Anki',
            'desc': 'Powerful, intelligent flash cards for effective learning.',
            'pkg': 'anki',
            'cmd': 'anki',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'anki.png'),
            'category': 'Education',
        },
        {
            'id': 'geogebra',
            'name': 'GeoGebra',
            'desc': 'Dynamic mathematics software for all levels of education.',
            'pkg': 'geogebra',
            'cmd': 'geogebra',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'geogebra.png'),
            'category': 'Education',
        },

        # Customization
        {
            'id': 'latte-dock',
            'name': 'Latte Dock',
            'desc': 'Dock based on Plasma frameworks for an elegant desktop.',
            'pkg': 'latte-dock',
            'cmd': 'latte-dock',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'latte.png'),
            'category': 'Customization',
        },
        {
            'id': 'conky',
            'name': 'Conky',
            'desc': 'Light-weight system monitor for X windows.',
            'pkg': 'conky',
            'cmd': 'conky',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'conky.png'),
            'category': 'Customization',
        },
        {
            'id': 'neofetch',
            'name': 'Neofetch',
            'desc': 'Command-line system information tool with ASCII art.',
            'pkg': 'neofetch',
            'cmd': 'neofetch',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'neofetch.png'),
            'category': 'Customization',
        },
        {
            'id': 'polybar',
            'name': 'Polybar',
            'desc': 'Fast and easy-to-use status bar for tiling window managers.',
            'pkg': 'polybar',
            'cmd': 'polybar',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'polybar.png'),
            'category': 'Customization',
        },

        # Web Browsers
        {
            'id': 'firefox',
            'name': 'Firefox',
            'desc': 'Fast, private & safe web browser from Mozilla.',
            'pkg': 'firefox',
            'cmd': 'firefox',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'firefox.png'),
            'category': 'Internet',
        },
        {
            'id': 'chromium',
            'name': 'Chromium',
            'desc': 'Open-source web browser project from Google.',
            'pkg': 'chromium',
            'cmd': 'chromium',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'chromium.png'),
            'category': 'Internet',
        },
        {
            'id': 'brave',
            'name': 'Brave Browser',
            'desc': 'Privacy-focused web browser with built-in ad blocker.',
            'pkg': 'brave-bin',
            'cmd': 'brave',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'brave.png'),
            'category': 'Internet',
        },
        {
            'id': 'opera',
            'name': 'Opera',
            'desc': 'Fast, secure, easy-to-use browser with built-in VPN.',
            'pkg': 'opera',
            'cmd': 'opera',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'opera.png'),
            'category': 'Internet',
        },

        # Text Editors & IDEs
        {
            'id': 'vim',
            'name': 'Vim',
            'desc': 'Highly configurable text editor built to enable efficient text editing.',
            'pkg': 'vim',
            'cmd': 'vim',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vim.png'),
            'category': 'Development',
        },
        {
            'id': 'neovim',
            'name': 'Neovim',
            'desc': 'Hyperextensible Vim-based text editor.',
            'pkg': 'neovim',
            'cmd': 'nvim',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'neovim.png'),
            'category': 'Development',
        },
        {
            'id': 'sublime-text',
            'name': 'Sublime Text',
            'desc': 'Sophisticated text editor for code, markup and prose.',
            'pkg': 'sublime-text-4',
            'cmd': 'subl',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'sublime.png'),
            'category': 'Development',
        },
        {
            'id': 'atom',
            'name': 'Atom',
            'desc': 'Hackable text editor for the 21st Century.',
            'pkg': 'atom',
            'cmd': 'atom',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'atom.png'),
            'category': 'Development',
        },
        {
            'id': 'intellij-idea',
            'name': 'IntelliJ IDEA',
            'desc': 'Powerful IDE for Java and other JVM languages.',
            'pkg': 'intellij-idea-community-edition',
            'cmd': 'idea',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'intellij.png'),
            'category': 'Development',
        },

        # Media & Entertainment
        {
            'id': 'spotify',
            'name': 'Spotify',
            'desc': 'Digital music streaming service with millions of songs.',
            'pkg': 'spotify',
            'cmd': 'spotify',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'spotify.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'mpv',
            'name': 'MPV',
            'desc': 'Free, open source, and cross-platform media player.',
            'pkg': 'mpv',
            'cmd': 'mpv',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'mpv.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'kdenlive',
            'name': 'Kdenlive',
            'desc': 'Free and open-source video editing software.',
            'pkg': 'kdenlive',
            'cmd': 'kdenlive',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'kdenlive.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'handbrake',
            'name': 'HandBrake',
            'desc': 'Open-source video transcoder for converting video files.',
            'pkg': 'handbrake',
            'cmd': 'ghb',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'handbrake.png'),
            'category': 'Multimedia',
        },

        # Graphics & Design
        {
            'id': 'inkscape',
            'name': 'Inkscape',
            'desc': 'Professional vector graphics editor for creating scalable graphics.',
            'pkg': 'inkscape',
            'cmd': 'inkscape',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'inkscape.png'),
            'category': 'Graphics',
        },
        {
            'id': 'krita',
            'name': 'Krita',
            'desc': 'Professional FREE and open source painting program.',
            'pkg': 'krita',
            'cmd': 'krita',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'krita.png'),
            'category': 'Graphics',
        },
        {
            'id': 'darktable',
            'name': 'Darktable',
            'desc': 'Open source photography workflow application and RAW developer.',
            'pkg': 'darktable',
            'cmd': 'darktable',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'darktable.png'),
            'category': 'Graphics',
        },
        {
            'id': 'rawtherapee',
            'name': 'RawTherapee',
            'desc': 'Powerful cross-platform raw photo processing program.',
            'pkg': 'rawtherapee',
            'cmd': 'rawtherapee',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'rawtherapee.png'),
            'category': 'Graphics',
        },

        # File Management
        {
            'id': 'nautilus',
            'name': 'Nautilus',
            'desc': 'GNOME file manager with clean and simple interface.',
            'pkg': 'nautilus',
            'cmd': 'nautilus',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nautilus.png'),
            'category': 'Utility',
        },
        {
            'id': 'thunar',
            'name': 'Thunar',
            'desc': 'Fast and easy to use file manager for Xfce desktop.',
            'pkg': 'thunar',
            'cmd': 'thunar',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'thunar.png'),
            'category': 'Utility',
        },
        {
            'id': 'ranger',
            'name': 'Ranger',
            'desc': 'Console file manager with VI key bindings.',
            'pkg': 'ranger',
            'cmd': 'ranger',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'ranger.png'),
            'category': 'Utility',
        },

        # Terminal Emulators
        {
            'id': 'kitty',
            'name': 'Kitty',
            'desc': 'Fast, feature-rich, GPU based terminal emulator.',
            'pkg': 'kitty',
            'cmd': 'kitty',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'kitty.png'),
            'category': 'System',
        },
        {
            'id': 'alacritty',
            'name': 'Alacritty',
            'desc': 'Cross-platform, GPU-accelerated terminal emulator.',
            'pkg': 'alacritty',
            'cmd': 'alacritty',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'alacritty.png'),
            'category': 'System',
        },
        {
            'id': 'terminator',
            'name': 'Terminator',
            'desc': 'Terminal emulator with support for multiple terminals in one window.',
            'pkg': 'terminator',
            'cmd': 'terminator',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'terminator.png'),
            'category': 'System',
        },

        # Productivity & Notes
        {
            'id': 'obsidian',
            'name': 'Obsidian',
            'desc': 'Powerful knowledge base that works on top of local folder of plain text files.',
            'pkg': 'obsidian',
            'cmd': 'obsidian',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'obsidian.png'),
            'category': 'Office',
        },
        {
            'id': 'joplin',
            'name': 'Joplin',
            'desc': 'Free, open source note taking and to-do application.',
            'pkg': 'joplin-appimage',
            'cmd': 'joplin',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'joplin.png'),
            'category': 'Office',
        },
        {
            'id': 'typora',
            'name': 'Typora',
            'desc': 'Minimal markdown editor with live preview.',
            'pkg': 'typora',
            'cmd': 'typora',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'typora.png'),
            'category': 'Office',
        },

        # Virtualization
        {
            'id': 'virtualbox',
            'name': 'VirtualBox',
            'desc': 'Powerful x86 and AMD64/Intel64 virtualization product.',
            'pkg': 'virtualbox',
            'cmd': 'virtualbox',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'virtualbox.png'),
            'category': 'System',
        },
        {
            'id': 'qemu',
            'name': 'QEMU',
            'desc': 'Generic and open source machine emulator and virtualizer.',
            'pkg': 'qemu-full',
            'cmd': 'qemu-system-x86_64',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'qemu.png'),
            'category': 'System',
        },

        # Network Tools
        {
            'id': 'wireshark',
            'name': 'Wireshark',
            'desc': 'Network protocol analyzer for troubleshooting and analysis.',
            'pkg': 'wireshark-qt',
            'cmd': 'wireshark',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'wireshark.png'),
            'category': 'Security',
        },
        {
            'id': 'nmap',
            'name': 'Nmap',
            'desc': 'Network discovery and security auditing utility.',
            'pkg': 'nmap',
            'cmd': 'nmap',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nmap.png'),
            'category': 'Security',
        },

        # More Games
        {
            'id': 'minecraft',
            'name': 'Minecraft Launcher',
            'desc': 'Official launcher for the popular sandbox game.',
            'pkg': 'minecraft-launcher',
            'cmd': 'minecraft-launcher',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'minecraft.png'),
            'category': 'Games',
        },
        {
            'id': 'retroarch',
            'name': 'RetroArch',
            'desc': 'Frontend for emulators, game engines and media players.',
            'pkg': 'retroarch',
            'cmd': 'retroarch',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'retroarch.png'),
            'category': 'Games',
        },

        # Database Tools
        {
            'id': 'dbeaver',
            'name': 'DBeaver',
            'desc': 'Universal database tool for developers and database administrators.',
            'pkg': 'dbeaver',
            'cmd': 'dbeaver',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'dbeaver.png'),
            'category': 'Development',
        },

        # More Education
        {
            'id': 'stellarium',
            'name': 'Stellarium',
            'desc': 'Free open source planetarium for your computer.',
            'pkg': 'stellarium',
            'cmd': 'stellarium',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'stellarium.png'),
            'category': 'Education',
        },
        {
            'id': 'kstars',
            'name': 'KStars',
            'desc': 'Desktop planetarium showing accurate night sky simulation.',
            'pkg': 'kstars',
            'cmd': 'kstars',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'kstars.png'),
            'category': 'Education',
        },

        # AUR Packages
        {
            'id': 'yay',
            'name': 'Yay',
            'desc': 'AUR helper written in Go for easy AUR package management.',
            'pkg': 'aur/yay',
            'cmd': 'yay',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'yay.png'),
            'category': 'Development',
        },
        {
            'id': 'paru',
            'name': 'Paru',
            'desc': 'Feature-rich AUR helper with pacman-like interface.',
            'pkg': 'aur/paru',
            'cmd': 'paru',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'paru.png'),
            'category': 'Development',
        },
        {
            'id': 'visual-studio-code-bin',
            'name': 'VS Code (Binary)',
            'desc': 'Official VS Code binary from Microsoft via AUR.',
            'pkg': 'aur/visual-studio-code-bin',
            'cmd': 'code',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vscode.png'),
            'category': 'Development',
        },
        {
            'id': 'discord-bin',
            'name': 'Discord (Binary)',
            'desc': 'Official Discord binary from AUR.',
            'pkg': 'aur/discord-bin',
            'cmd': 'discord',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'discord.png'),
            'category': 'Communication',
        },
        {
            'id': 'spotify-bin',
            'name': 'Spotify (Binary)',
            'desc': 'Official Spotify binary from AUR.',
            'pkg': 'aur/spotify-bin',
            'cmd': 'spotify',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'spotify.png'),
            'category': 'Multimedia',
        },

        # Flatpak Packages
        {
            'id': 'org.gnome.Evolution',
            'name': 'Evolution',
            'desc': 'GNOME email and calendar application.',
            'pkg': 'org.gnome.Evolution.flatpak',
            'cmd': 'evolution',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'evolution.png'),
            'category': 'Internet',
        },
        {
            'id': 'org.gnome.Boxes',
            'name': 'GNOME Boxes',
            'desc': 'Simple GNOME application to access remote or virtual systems.',
            'pkg': 'org.gnome.Boxes.flatpak',
            'cmd': 'gnome-boxes',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'boxes.png'),
            'category': 'System',
        },
        {
            'id': 'com.github.tchx84.Flatseal',
            'name': 'Flatseal',
            'desc': 'Manage Flatpak permissions graphically.',
            'pkg': 'com.github.tchx84.Flatseal.flatpak',
            'cmd': 'flatseal',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'flatseal.png'),
            'category': 'Utility',
        },
        {
            'id': 'org.kde.kdenlive',
            'name': 'Kdenlive (Flatpak)',
            'desc': 'Free and open-source video editing software (Flatpak version).',
            'pkg': 'org.kde.kdenlive.flatpak',
            'cmd': 'kdenlive',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'kdenlive.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'org.gimp.GIMP',
            'name': 'GIMP (Flatpak)',
            'desc': 'GNU Image Manipulation Program (Flatpak version).',
            'pkg': 'org.gimp.GIMP.flatpak',
            'cmd': 'gimp',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gimp.png'),
            'category': 'Graphics',
        },

        # NPM Packages
        {
            'id': 'npm-http-server',
            'name': 'HTTP Server',
            'desc': 'Simple zero-configuration command-line HTTP server.',
            'pkg': 'npm-http-server',
            'cmd': 'http-server',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nodejs.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-typescript',
            'name': 'TypeScript',
            'desc': 'TypeScript is a typed superset of JavaScript.',
            'pkg': 'npm-typescript',
            'cmd': 'tsc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'typescript.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-webpack',
            'name': 'Webpack',
            'desc': 'Module bundler for JavaScript applications.',
            'pkg': 'npm-webpack',
            'cmd': 'webpack',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'webpack.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-eslint',
            'name': 'ESLint',
            'desc': 'Pluggable JavaScript linter for identifying and reporting patterns.',
            'pkg': 'npm-eslint',
            'cmd': 'eslint',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'eslint.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-prettier',
            'name': 'Prettier',
            'desc': 'Code formatter for JavaScript, CSS, JSON and more.',
            'pkg': 'npm-prettier',
            'cmd': 'prettier',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'prettier.png'),
            'category': 'Development',
        },

        # More AUR Packages
        {
            'id': 'google-chrome',
            'name': 'Google Chrome',
            'desc': 'Fast, secure web browser from Google.',
            'pkg': 'aur/google-chrome',
            'cmd': 'google-chrome',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'chrome.png'),
            'category': 'Internet',
        },
        {
            'id': 'slack-desktop',
            'name': 'Slack',
            'desc': 'Team messaging and collaboration platform.',
            'pkg': 'aur/slack-desktop',
            'cmd': 'slack',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'slack.png'),
            'category': 'Communication',
        },
        {
            'id': 'teams',
            'name': 'Microsoft Teams',
            'desc': 'Microsoft Teams for Linux.',
            'pkg': 'aur/teams',
            'cmd': 'teams',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'teams.png'),
            'category': 'Communication',
        },
        {
            'id': 'postman',
            'name': 'Postman',
            'desc': 'API development and testing platform.',
            'pkg': 'aur/postman-bin',
            'cmd': 'postman',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'postman.png'),
            'category': 'Development',
        },
        # More Flatpak Packages
        {
            'id': 'org.mozilla.firefox',
            'name': 'Firefox (Flatpak)',
            'desc': 'Fast, private & safe web browser (Flatpak version).',
            'pkg': 'org.mozilla.firefox.flatpak',
            'cmd': 'firefox',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'firefox.png'),
            'category': 'Internet',
        },
        {
            'id': 'org.blender.Blender',
            'name': 'Blender (Flatpak)',
            'desc': '3D modeling and animation software (Flatpak version).',
            'pkg': 'org.blender.Blender.flatpak',
            'cmd': 'blender',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'blender.png'),
            'category': 'Graphics',
        },
        {
            'id': 'org.inkscape.Inkscape',
            'name': 'Inkscape (Flatpak)',
            'desc': 'Vector graphics editor (Flatpak version).',
            'pkg': 'org.inkscape.Inkscape.flatpak',
            'cmd': 'inkscape',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'inkscape.png'),
            'category': 'Graphics',
        },
        {
            'id': 'org.audacityteam.Audacity',
            'name': 'Audacity (Flatpak)',
            'desc': 'Audio editor and recorder (Flatpak version).',
            'pkg': 'org.audacityteam.Audacity.flatpak',
            'cmd': 'audacity',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'audacity.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'org.libreoffice.LibreOffice',
            'name': 'LibreOffice (Flatpak)',
            'desc': 'Office suite (Flatpak version).',
            'pkg': 'org.libreoffice.LibreOffice.flatpak',
            'cmd': 'libreoffice',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'libreoffice.png'),
            'category': 'Office',
        },

        # More NPM Packages
        {
            'id': 'npm-react',
            'name': 'React',
            'desc': 'JavaScript library for building user interfaces.',
            'pkg': 'npm-react',
            'cmd': 'react',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'react.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-vue',
            'name': 'Vue.js',
            'desc': 'Progressive JavaScript framework for building UIs.',
            'pkg': 'npm-vue',
            'cmd': 'vue',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vue.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-angular',
            'name': 'Angular',
            'desc': 'Platform for building mobile and desktop web applications.',
            'pkg': 'npm-angular',
            'cmd': 'ng',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'angular.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-express',
            'name': 'Express.js',
            'desc': 'Fast, unopinionated web framework for Node.js.',
            'pkg': 'npm-express',
            'cmd': 'express',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'express.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-jest',
            'name': 'Jest',
            'desc': 'JavaScript testing framework with focus on simplicity.',
            'pkg': 'npm-jest',
            'cmd': 'jest',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'jest.png'),
            'category': 'Development',
        },
        # More AUR Packages
        {
            'id': 'visual-studio-code-insiders',
            'name': 'VS Code Insiders',
            'desc': 'Insiders build of Visual Studio Code.',
            'pkg': 'aur/visual-studio-code-insiders-bin',
            'cmd': 'code-insiders',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vscode.png'),
            'category': 'Development',
        },
        {
            'id': 'jetbrains-toolbox',
            'name': 'JetBrains Toolbox',
            'desc': 'JetBrains IDE management tool.',
            'pkg': 'aur/jetbrains-toolbox',
            'cmd': 'jetbrains-toolbox',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'jetbrains.png'),
            'category': 'Development',
        },
        {
            'id': 'docker-desktop',
            'name': 'Docker Desktop',
            'desc': 'Docker containerization platform.',
            'pkg': 'aur/docker-desktop',
            'cmd': 'docker',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'docker.png'),
            'category': 'Development',
        },
        {
            'id': 'figma',
            'name': 'Figma',
            'desc': 'Collaborative design and prototyping tool.',
            'pkg': 'aur/figma-linux',
            'cmd': 'figma',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'figma.png'),
            'category': 'Graphics',
        },
        # More Flatpak Packages
        {
            'id': 'org.gnome.Calendar',
            'name': 'GNOME Calendar',
            'desc': 'Simple calendar application (Flatpak).',
            'pkg': 'org.gnome.Calendar.flatpak',
            'cmd': 'gnome-calendar',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'calendar.png'),
            'category': 'Office',
        },
        {
            'id': 'org.gnome.Maps',
            'name': 'GNOME Maps',
            'desc': 'Map application (Flatpak).',
            'pkg': 'org.gnome.Maps.flatpak',
            'cmd': 'gnome-maps',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'maps.png'),
            'category': 'Utility',
        },
        {
            'id': 'org.gnome.Weather',
            'name': 'GNOME Weather',
            'desc': 'Weather application (Flatpak).',
            'pkg': 'org.gnome.Weather.flatpak',
            'cmd': 'gnome-weather',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'weather.png'),
            'category': 'Utility',
        },
        {
            'id': 'org.gnome.Photos',
            'name': 'GNOME Photos',
            'desc': 'Photo management application (Flatpak).',
            'pkg': 'org.gnome.Photos.flatpak',
            'cmd': 'gnome-photos',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'photos.png'),
            'category': 'Graphics',
        },
        {
            'id': 'org.gnome.Music',
            'name': 'GNOME Music',
            'desc': 'Music player application (Flatpak).',
            'pkg': 'org.gnome.Music.flatpak',
            'cmd': 'gnome-music',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'music.png'),
            'category': 'Multimedia',
        },
        # More NPM Packages
        {
            'id': 'npm-next',
            'name': 'Next.js',
            'desc': 'React framework for production applications.',
            'pkg': 'npm-next',
            'cmd': 'next',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nextjs.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-nuxt',
            'name': 'Nuxt.js',
            'desc': 'Vue.js framework for production applications.',
            'pkg': 'npm-nuxt',
            'cmd': 'nuxt',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nuxt.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-gatsby',
            'name': 'Gatsby',
            'desc': 'Static site generator with React.',
            'pkg': 'npm-gatsby',
            'cmd': 'gatsby',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gatsby.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-svelte',
            'name': 'Svelte',
            'desc': 'Compiler for building UI components.',
            'pkg': 'npm-svelte',
            'cmd': 'svelte',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'svelte.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-tailwindcss',
            'name': 'Tailwind CSS',
            'desc': 'Utility-first CSS framework.',
            'pkg': 'npm-tailwindcss',
            'cmd': 'tailwindcss',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'tailwind.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-bootstrap',
            'name': 'Bootstrap',
            'desc': 'Popular CSS framework for responsive design.',
            'pkg': 'npm-bootstrap',
            'cmd': 'bootstrap',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'bootstrap.png'),
            'category': 'Development',
        },
        {
            'id': 'npm-graphql',
            'name': 'GraphQL',
            'desc': 'Query language for APIs.',
            'pkg': 'npm-graphql',
            'cmd': 'graphql',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'graphql.png'),
            'category': 'Development',
        },
        # ── Added popular packages ──
        {
            'id': 'fastfetch',
            'name': 'Fastfetch',
            'desc': 'Fast, feature-rich system information tool.',
            'pkg': 'fastfetch',
            'cmd': 'fastfetch',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'fastfetch.png'),
            'category': 'System',
        },
        {
            'id': 'ncdu',
            'name': 'ncdu',
            'desc': 'Disk usage analyzer with ncurses interface.',
            'pkg': 'ncdu',
            'cmd': 'ncdu',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'ncdu.png'),
            'category': 'System',
        },
        {
            'id': 'stacer',
            'name': 'Stacer',
            'desc': 'System optimizer and monitoring tool.',
            'pkg': 'aur/stacer',
            'cmd': 'stacer',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'stacer.png'),
            'category': 'System',
        },
        {
            'id': 'glances',
            'name': 'Glances',
            'desc': 'Cross-platform system monitoring in the terminal.',
            'pkg': 'glances',
            'cmd': 'glances',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'glances.png'),
            'category': 'Monitor',
        },
        {
            'id': 's-tui',
            'name': 's-tui',
            'desc': 'Terminal UI for CPU stress and monitoring.',
            'pkg': 's-tui',
            'cmd': 's-tui',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 's-tui.png'),
            'category': 'Monitor',
        },
        {
            'id': 'rustup',
            'name': 'Rust',
            'desc': 'Rust programming language toolchain manager.',
            'pkg': 'rustup',
            'cmd': 'rustup',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'rust.png'),
            'category': 'Development',
        },
        {
            'id': 'go',
            'name': 'Go',
            'desc': 'Open source programming language by Google.',
            'pkg': 'go',
            'cmd': 'go',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'go.png'),
            'category': 'Development',
        },
        {
            'id': 'cmake',
            'name': 'CMake',
            'desc': 'Cross-platform build system generator.',
            'pkg': 'cmake',
            'cmd': 'cmake',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'cmake.png'),
            'category': 'Development',
        },
        {
            'id': 'gcc',
            'name': 'GCC',
            'desc': 'GNU compiler collection for C, C++ and more.',
            'pkg': 'gcc',
            'cmd': 'gcc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gcc.png'),
            'category': 'Development',
        },
        {
            'id': 'gdb',
            'name': 'GDB',
            'desc': 'GNU debugger for program debugging.',
            'pkg': 'gdb',
            'cmd': 'gdb',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gdb.png'),
            'category': 'Development',
        },
        {
            'id': 'ripgrep',
            'name': 'ripgrep',
            'desc': 'Recursively search directories for regex patterns.',
            'pkg': 'ripgrep',
            'cmd': 'rg',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'ripgrep.png'),
            'category': 'Development',
        },
        {
            'id': 'fd',
            'name': 'fd',
            'desc': 'Simple, fast alternative to find.',
            'pkg': 'fd',
            'cmd': 'fd',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'fd.png'),
            'category': 'Development',
        },
        {
            'id': 'jq',
            'name': 'jq',
            'desc': 'Lightweight JSON processor for the command line.',
            'pkg': 'jq',
            'cmd': 'jq',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'jq.png'),
            'category': 'Development',
        },
        {
            'id': 'tmux',
            'name': 'tmux',
            'desc': 'Terminal multiplexer for multiple sessions.',
            'pkg': 'tmux',
            'cmd': 'tmux',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'tmux.png'),
            'category': 'Utility',
        },
        {
            'id': 'zsh',
            'name': 'Zsh',
            'desc': 'Powerful shell with advanced completion.',
            'pkg': 'zsh',
            'cmd': 'zsh',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'zsh.png'),
            'category': 'Utility',
        },
        {
            'id': 'fish',
            'name': 'Fish',
            'desc': 'Friendly interactive shell.',
            'pkg': 'fish',
            'cmd': 'fish',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'fish.png'),
            'category': 'Utility',
        },
        {
            'id': 'yarn',
            'name': 'Yarn',
            'desc': 'Fast, reliable JavaScript package manager.',
            'pkg': 'yarn',
            'cmd': 'yarn',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'yarn.png'),
            'category': 'Development',
        },
        {
            'id': 'pnpm',
            'name': 'pnpm',
            'desc': 'Fast, disk-space efficient package manager.',
            'pkg': 'pnpm',
            'cmd': 'pnpm',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'pnpm.png'),
            'category': 'Development',
        },
        {
            'id': 'deno',
            'name': 'Deno',
            'desc': 'Modern JavaScript and TypeScript runtime.',
            'pkg': 'deno',
            'cmd': 'deno',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'deno.png'),
            'category': 'Development',
        },
        {
            'id': 'bun',
            'name': 'Bun',
            'desc': 'All-in-one JavaScript runtime and toolkit.',
            'pkg': 'bun',
            'cmd': 'bun',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'bun.png'),
            'category': 'Development',
        },
        {
            'id': 'yt-dlp',
            'name': 'yt-dlp',
            'desc': 'Command-line video downloader with wide support.',
            'pkg': 'yt-dlp',
            'cmd': 'yt-dlp',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'yt-dlp.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'ffmpeg',
            'name': 'FFmpeg',
            'desc': 'Complete cross-platform multimedia framework.',
            'pkg': 'ffmpeg',
            'cmd': 'ffmpeg',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'ffmpeg.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'flameshot',
            'name': 'Flameshot',
            'desc': 'Powerful yet simple-to-use screenshot tool.',
            'pkg': 'flameshot',
            'cmd': 'flameshot',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'flameshot.png'),
            'category': 'Utility',
        },
        {
            'id': 'strawberry',
            'name': 'Strawberry',
            'desc': 'Music player and music collection organizer.',
            'pkg': 'strawberry',
            'cmd': 'strawberry',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'strawberry.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'mangohud',
            'name': 'MangoHud',
            'desc': 'Vulkan and OpenGL overlay for monitoring gaming.',
            'pkg': 'mangohud',
            'cmd': 'mangohud',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'mangohud.png'),
            'category': 'Games',
        },
        {
            'id': 'gamescope',
            'name': 'Gamescope',
            'desc': 'SteamOS session compositing window manager.',
            'pkg': 'gamescope',
            'cmd': 'gamescope',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gamescope.png'),
            'category': 'Games',
        },
        {
            'id': 'wine',
            'name': 'Wine',
            'desc': 'Run Windows applications on Linux.',
            'pkg': 'wine',
            'cmd': 'wine',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'wine.png'),
            'category': 'Games',
        },
        {
            'id': 'winetricks',
            'name': 'Winetricks',
            'desc': 'Script to install common Windows apps in Wine.',
            'pkg': 'winetricks',
            'cmd': 'winetricks',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'winetricks.png'),
            'category': 'Games',
        },
        {
            'id': 'element-desktop',
            'name': 'Element',
            'desc': 'Secure chat app for the Matrix network.',
            'pkg': 'element-desktop',
            'cmd': 'element-desktop',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'element.png'),
            'category': 'Communication',
        },
        {
            'id': 'firejail',
            'name': 'Firejail',
            'desc': 'Sandbox for running untrusted applications.',
            'pkg': 'firejail',
            'cmd': 'firejail',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'firejail.png'),
            'category': 'Security',
        },
        {
            'id': 'gufw',
            'name': 'Gufw',
            'desc': 'Graphical interface for managing UFW firewall.',
            'pkg': 'gufw',
            'cmd': 'gufw',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'gufw.png'),
            'category': 'Security',
        },
        {
            'id': 'veracrypt',
            'name': 'VeraCrypt',
            'desc': 'Cross-platform disk encryption software.',
            'pkg': 'veracrypt',
            'cmd': 'veracrypt',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'veracrypt.png'),
            'category': 'Security',
        },
        {
            'id': 'keepass',
            'name': 'KeePass',
            'desc': 'Open-source password manager (KeePass2 protocol).',
            'pkg': 'keepass',
            'cmd': 'keepass',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'keepass.png'),
            'category': 'Security',
        },
        {
            'id': 'copyq',
            'name': 'CopyQ',
            'desc': 'Advanced clipboard manager with search and editing.',
            'pkg': 'copyq',
            'cmd': 'copyq',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'copyq.png'),
            'category': 'Utility',
        },
        {
            'id': 'syncthing',
            'name': 'Syncthing',
            'desc': 'Continuous file synchronization between devices.',
            'pkg': 'syncthing',
            'cmd': 'syncthing',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'syncthing.png'),
            'category': 'Utility',
        },
        {
            'id': 'borgbackup',
            'name': 'BorgBackup',
            'desc': 'Deduplicating archiver with compression.',
            'pkg': 'borg',
            'cmd': 'borg',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'borg.png'),
            'category': 'Backup',
        },
        {
            'id': 'vorta',
            'name': 'Vorta',
            'desc': 'Backup client for BorgBackup with GUI.',
            'pkg': 'vorta',
            'cmd': 'vorta',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'vorta.png'),
            'category': 'Backup',
        },
        {
            'id': 'okular',
            'name': 'Okular',
            'desc': 'Universal document viewer for PDF and more.',
            'pkg': 'okular',
            'cmd': 'okular',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'okular.png'),
            'category': 'Office',
        },
        {
            'id': 'pandoc',
            'name': 'Pandoc',
            'desc': 'Universal document format converter.',
            'pkg': 'pandoc-cli',
            'cmd': 'pandoc',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'pandoc.png'),
            'category': 'Office',
        },
        {
            'id': 'zathura',
            'name': 'Zathura',
            'desc': 'Minimal, keyboard-driven document viewer.',
            'pkg': 'zathura',
            'cmd': 'zathura',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'zathura.png'),
            'category': 'Office',
        },
        {
            'id': 'xournalpp',
            'name': 'Xournal++',
            'desc': 'Handwriting note-taking and PDF annotation.',
            'pkg': 'xournalpp',
            'cmd': 'xournalpp',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'xournalpp.png'),
            'category': 'Office',
        },
        {
            'id': 'rnote',
            'name': 'Rnote',
            'desc': 'Vector-based drawing app for sketching and notes.',
            'pkg': 'rnote',
            'cmd': 'rnote',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'rnote.png'),
            'category': 'Graphics',
        },
        {
            'id': 'pinta',
            'name': 'Pinta',
            'desc': 'Simple GTK drawing and image editing program.',
            'pkg': 'pinta',
            'cmd': 'pinta',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'pinta.png'),
            'category': 'Graphics',
        },
        {
            'id': 'imagemagick',
            'name': 'ImageMagick',
            'desc': 'Image manipulation and conversion tools.',
            'pkg': 'imagemagick',
            'cmd': 'magick',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'imagemagick.png'),
            'category': 'Graphics',
        },
        {
            'id': 'feh',
            'name': 'feh',
            'desc': 'Lightweight image viewer for X11.',
            'pkg': 'feh',
            'cmd': 'feh',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'feh.png'),
            'category': 'Graphics',
        },
        {
            'id': 'nextcloud-client',
            'name': 'Nextcloud',
            'desc': 'Desktop client for Nextcloud file sync.',
            'pkg': 'nextcloud-client',
            'cmd': 'nextcloud-client',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'nextcloud.png'),
            'category': 'Internet',
        },
        {
            'id': 'deluge',
            'name': 'Deluge',
            'desc': 'Lightweight BitTorrent client.',
            'pkg': 'deluge',
            'cmd': 'deluge',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'deluge.png'),
            'category': 'Internet',
        },
        {
            'id': 'rofi',
            'name': 'Rofi',
            'desc': 'Application launcher and window switcher.',
            'pkg': 'rofi',
            'cmd': 'rofi',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'rofi.png'),
            'category': 'Customization',
        },
        {
            'id': 'waybar',
            'name': 'Waybar',
            'desc': 'Highly customizable status bar for Wayland.',
            'pkg': 'waybar',
            'cmd': 'waybar',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'waybar.png'),
            'category': 'Customization',
        },
        {
            'id': 'picom',
            'name': 'Picom',
            'desc': 'Lightweight compositor for X11 with effects.',
            'pkg': 'picom',
            'cmd': 'picom',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'picom.png'),
            'category': 'Customization',
        },
        {
            'id': 'grub-customizer',
            'name': 'GRUB Customizer',
            'desc': 'Graphical tool to configure the GRUB boot loader.',
            'pkg': 'aur/grub-customizer',
            'cmd': 'grub-customizer',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'grub-customizer.png'),
            'category': 'System',
        },
        {
            'id': 'snapper',
            'name': 'Snapper',
            'desc': 'Filesystem snapshot management for Linux.',
            'pkg': 'snapper',
            'cmd': 'snapper',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'snapper.png'),
            'category': 'Backup',
        },
        {
            'id': 'podman',
            'name': 'Podman',
            'desc': 'Daemonless container engine for Linux.',
            'pkg': 'podman',
            'cmd': 'podman',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'podman.png'),
            'category': 'Development',
        },
        {
            'id': 'lazygit',
            'name': 'Lazygit',
            'desc': 'Simple terminal UI for git commands.',
            'pkg': 'lazygit',
            'cmd': 'lazygit',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'lazygit.png'),
            'category': 'Development',
        },
        {
            'id': 'neovim-qt',
            'name': 'Neovim-Qt',
            'desc': 'GUI client for Neovim.',
            'pkg': 'neovim-qt',
            'cmd': 'nvim-qt',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'neovim-qt.png'),
            'category': 'Development',
        },
        {
            'id': 'lua',
            'name': 'Lua',
            'desc': 'Lightweight embeddable scripting language.',
            'pkg': 'lua',
            'cmd': 'lua',
            'icon': os.path.join(PLUGINS_ITEMS_DIR, 'lua.png'),
            'category': 'Development',
        },
    ]
    return _shuffle_plugins(plugins)


def _shuffle_plugins(plugins):
    """Shuffle plugins while keeping initial popular items at the top"""
    if len(plugins) <= 8:
        return plugins
    popular = plugins[:8]
    rest = plugins[8:]
    random.shuffle(rest)
    return popular + rest
